import { Inter, Poppins, Montserrat } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "./utils/Toastify";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
  variable: "--font-inter",
});

const poppins = Poppins({
  weight: ["400", "600"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const montserrat = Montserrat({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins.variable} ${montserrat.variable}`}>
        {children}
        <ToastContainer/>
      </body>
    </html>
  );
}
